version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      spring-boot-dependencies:
        patterns:
          - org.springframework.*
      aws-sdk:
        patterns:
          - software.amazon.awssdk:*
      jackson:
        patterns:
          - com.fasterxml.jackson.*
          - io.jsonwebtoken:*

  - package-ecosystem: pip
    directory: /recommendation-service
    schedule:
      interval: weekly
    groups:
      python-deps:
        patterns:
          - "*"
